plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'org.jetbrains.kotlin.jvm'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    include library('io.projectreactor:reactor-core:3.5.5')
    include library('org.reactivestreams:reactive-streams:1.0.4')
    include library('org.hjson:hjson:3.1.0')


    // Mod dependencies
    modImplementation 'com.electronwill.night-config:core:3.6.5'
    modImplementation 'com.electronwill.night-config:toml:3.6.5'

    // Essential mods.
    modImplementation "com.terraformersmc:modmenu:11.0.2", {
        exclude module: "fabric-api"
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}
