# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
systemProp.gradle.internal.repository.retry.maxRetries=50
systemProp.gradle.internal.repository.retry.initialBackoff=2000

# Fabric Properties
# check these on https://fabricmc.net/develop
quantum_version=0.0.5
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=dev.ultreon
archives_base_name=exit-confirmation

# Dependencies
mixin_version=0.15.5+mixin.0.8.7