# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=3.1.0-hotfix.1
group=dev.ultreon.mods
java_version=21
# Common
minecraft_version=1.21.2
mod_name=Exit Confirmation
mod_author=Omnixerio Studios
mod_id=exit_confirm
license=All Rights Reserved
credits=
description=An overcomplicated exit confirmation screen that shows up when trying to close Minecraft.
minecraft_version_range=[1.21.2, 1.21.3)
neo_form_version=1.21.2-20241022.151510
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.106.1+1.21.2
fabric_loader_version=0.18.0
cca_version=6.1.1
# Forge
forge_version=52.0.29
forge_loader_version_range=[52,)
# NeoForge
neoforge_version=21.2.1-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
ultreonlib_version=1.5.0
