import org.jetbrains.kotlin.gradle.dsl.JvmTarget
plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at.absolutePath]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    maven {
        name "ultreonMavenSnapshots"
        url "https://maven.ultreon.dev/snapshots"
    }
    maven {
        name "ultreonMavenReleases"
        url "https://maven.ultreon.dev/releases"
    }
}

dependencies {
    compileOnlyApi("org.spongepowered:mixin:0.8.5")
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnlyApi("io.github.llamalad7:mixinextras-common:0.4.1")
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")

    // Extra dependencies
    library("io.projectreactor:reactor-core:3.5.5")
    library("org.hjson:hjson:3.1.0")

    compileOnly("dev.ultreon.mods:xinexlib-common-1.21.1:0.1.0-SNAPSHOT")

    compileOnly("com.electronwill.night-config:core:3.6.3")
    compileOnly("com.electronwill.night-config:toml:3.6.3")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

kotlin {
    jvmToolchain 21
}

compileKotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
    }
}

classes {
    finalizedBy("copyKotlinClasses")
}

tasks.register("copyKotlinClasses") {
    doLast {
        copy {
            from fileTree("$projectDir/build/classes/kotlin/main")
            into file("$projectDir/build/classes/java/main")
        }
    }
}

jar.mustRunAfter("copyKotlinClasses")

jar {
    duplicatesStrategy DuplicatesStrategy.EXCLUDE
}

compileKotlin {
    outputs.dir("$projectDir/build/classes/java/main")
}
