plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at.absolutePath]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id.toString()
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        clientData {
            clientData()
        }
        serverData {
            serverData()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    additionalClasspath {
        extendsFrom api
    }

    clientAdditionalRuntimeClasspath.extendsFrom additionalClasspath
    serverAdditionalRuntimeClasspath.extendsFrom additionalClasspath
    dataAdditionalRuntimeClasspath.extendsFrom additionalClasspath
}

dependencies {
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
